- name: Initialize node hostnames
  hosts: k8s
  become: true

  tasks:

    # =====================================================
    # hostname 설정
    # =====================================================
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"

    # =====================================================
    # /etc/hosts 수정
    # =====================================================
    - name: Update /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: "127.0.1.1 {{ inventory_hostname }}"

    # =====================================================
    # hostname 확인
    # =====================================================
    - name: Check hostname
      shell: hostname
      register: hostname_result

    - name: Print hostname
      debug:
        msg: "{{ hostname_result.stdout }}"
