- name: VM precheck
  hosts: k8s
  become: true

  tasks:
    - name: Stop apt background services
      systemd:
        name: "{{ item }}"
        state: stopped
      loop:
        - unattended-upgrades
        - apt-daily.timer
        - apt-daily-upgrade.timer
        - apt-daily.service
        - apt-daily-upgrade.service
      ignore_errors: true

    - name: Fix interrupted dpkg state
      command: dpkg --configure -a
      register: dpkg_result
      retries: 5
      delay: 10
      until: dpkg_result.rc == 0
      changed_when: false

    - name: Safe apt update
      apt:
        update_cache: yes
        lock_timeout: 300
      register: apt_result
      retries: 10
      delay: 10
      until: apt_result is succeeded
