# =========================================================
# CP2, CP3 - Control Plane Join
# =========================================================
- name: Join additional control planes
  hosts: cp2,cp3
  become: true
  serial: 1

  tasks:

    - name: Join control plane
      shell: >
        {{ hostvars['cp1']['worker_join_cmd'] }}
        --control-plane
        --apiserver-advertise-address {{ node_ip | default(ansible_host) }}
        --certificate-key {{ hostvars['cp1']['cert_key'] }}
      args:
        creates: /etc/kubernetes/admin.conf

    # =====================================================
    # 2. kubeconfig 디렉토리 생성
    # =====================================================
    - name: Setup kubeconfig directory
      file:
        path: /home/kosa/.kube
        state: directory
        owner: kosa
        group: kosa

    # =====================================================
    # 3. kubeconfig 복사
    # =====================================================
    - name: Copy kubeconfig
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kosa/.kube/config
        remote_src: yes
        owner: kosa
        group: kosa


# =========================================================
# Worker Nodes Join
# =========================================================
- name: Join worker nodes
  hosts: workers
  become: true
  become_user: root

  tasks:

    - name: Join worker
      shell: "{{ hostvars['cp1']['worker_join_cmd'] }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
