- import_playbook: playbook/00_cp1-init.yml
- import_playbook: playbook/01_pre.yml
- import_playbook: playbook/02_setup.yml
- import_playbook: playbook/03_init.yml
- import_playbook: playbook/04_join.yml
- import_playbook: playbook/05_post.yml

# 실행
# ansible-playbook playbook.yml